<CustButton@Button>:
    font_size: 32
    color: 0, 0, 0, 1
    size: 150, 50
    background_normal: ''
    background_down: 'bkgrd-down-color.png'
    background_color: .88, .88, .88, 1

<CustomWidget>:
    CustButton:
        text: "Bless are the Ori!"
        pos: root.x, 200
    CustButton:
        text: "Live long and prosper"
        pos: 200, root.y
    CustButton:
        text: "May the force be with you"
        pos: 200, 400